
<?php

$siglas = array('3ª/SR' => '3ª/SR',
				 '3ª/CGE'=>'3ª/CGE',
				 '3ª/GB' => '3ª/GB',
				'3ª/CP' => '3ª/CP' ,
				'3ª/AJ' => '3ª/AJ',
				'3ª/SL' => '3ª/SL',
				'3ª/GRR'=>'3ª/GRR' ,
				'3ª/GRR/UMA'=>'3ª/GRR/UMA' ,
				'3ª/GRR/USA' =>'3ª/GRR/USA',
				'3ª/GRR/UDT' =>'3ª/GRR/UDT',
				'3ª/GRD'=> '3ª/GRD' ,
				'3ª/GRD/UEP'=> '3ª/GRD/UEP',
				'3ª/GRD/UIP'=>'3ª/GRD/UIP',
				'3ª/GRD/UOP'=> '3ª/GRD/UOP',
				'3ª/GRI'=>'3ª/GRI',
				'3ª/GRI/UGE' => '3ª/GRI/UGE',
				'3ª/GRI/UAP'=>'3ª/GRI/UAP',
				'3ª/GRI/UAF' =>'3ª/GRI/UAF',
				'3ª/GRA' =>'3ª/GRA',
				'3ª/GRA/UGP' =>'3ª/GRA/UGP',
				'3ª/GRA/USA' => '3ª/GRA/USA',
				'3ª/GRA/UCB' => '3ª/GRA/UCB',
				'3ª/GRA/UFN' => '3ª/GRA/UFN',
				'3ª/GRA/UFN/SCB' => '3ª/GRA/UFN/SCB' ,
				'3ª/GRG' => '3ª/GRG',
				'3ª/GRG/UTI' => '3ª/GRG/UTI',
				'3ª/GRG/UPO' => '3ª/GRG/UPO',
				'3ª/GRG/UMC' =>  '3ª/GRG/UMC',
				'3ª/EJT' => '3ª/EJT',
				'3ª/ESA' => '3ª/ESA',
				'3ª/CIB' => '3ª/CIB',
				'CONSELHO DE ADMINISTRAÇÃO  CONSAD' => 'CONSELHO DE ADMINISTRAÇÃO  CONSAD',
'DIRETORIA EXECUTIVA  DEX' => 'DIRETORIA EXECUTIVA  DEX',
'CONSELHO FISCAL  CONFIS' => 'CONSELHO FISCAL  CONFIS',
'PRESIDÊNCIA  PR' => 'PRESIDÊNCIA  PR',
'Gabinete  PR/GB'  => 'Gabinete  PR/GB' ,
'Ouvidoria  PR/OV' => 'Ouvidoria  PR/OV',
'Auditoria Interna  PR/AU' => 'Auditoria Interna  PR/AU',
'Unidade de Apoio e Informação  PR/AU/UIN' => 'Unidade de Apoio e Informação  PR/AU/UIN',
'Unidade de Acompanhamento e Avaliação de Programas  PR/AU/UAP' => 'Unidade de Acompanhamento e Avaliação de Programas  PR/AU/UAP',
'Unidade de Acompanhamento e Avaliação da Gestão  PR/AU/UAG' => 'Unidade de Acompanhamento e Avaliação da Gestão  PR/AU/UAG',
'Assessoria Jurídica  PR/AJ' =>  'Assessoria Jurídica  PR/AJ',
'Unidade de Assuntos Administrativos  PR/AJ/UAA' => 'Unidade de Assuntos Administrativos  PR/AJ/UAA',
'Unidade do Contencioso  PR/AJ/UCO' => 'Unidade do Contencioso  PR/AJ/UCO',
'Assessoria de Comunicação e Promoção Institucional  PR/ACP' => 'Assessoria de Comunicação e Promoção Institucional  PR/ACP',
'Secretaria de Órgãos Colegiados  PR/SC' => 'Secretaria de Órgãos Colegiados  PR/SC',
'Secretaria de Licitações  PR/SL' => 'Secretaria de Licitações  PR/SL',
'Escritório de Representação de Recife  PR/ERE' => 'Escritório de Representação de Recife  PR/ERE',
'Escritório de Representação de Salvador  PR/ESA' => 'Escritório de Representação de Salvador  PR/ESA',
'Escritório de Representação de Belo Horizonte  PR/EBH' => 'Escritório de Representação de Belo Horizonte  PR/EBH',
'ÁREA DE REVITALIZAÇÃO DAS BACIAS HIDROGRÁFICAS  AR' => 'ÁREA DE REVITALIZAÇÃO DAS BACIAS HIDROGRÁFICAS  AR',
'Secretaria Executiva  AR/SE' =>  'Secretaria Executiva  AR/SE',
'Gerência de Meio Ambiente  AR/GMA' =>  'Gerência de Meio Ambiente  AR/GMA',
'Unidade de Gestão Ambiental e Licenciamento  AR/GMA/UGA'  => 'Unidade de Gestão Ambiental e Licenciamento  AR/GMA/UGA',
'Gerência de Empreendimentos Sócioambientais  AR/GSA' => 'Gerência de Empreendimentos Sócioambientais  AR/GSA',
'Unidade de Conservação da Água, Solo e Recursos Florestais  AR/GSA/UCF' => 'Unidade de Conservação da Água, Solo e Recursos Florestais  AR/GSA/UCF',
'Unidade de Gestão das Ações de Revitalização  AR/GSA/UAR' => 'Unidade de Gestão das Ações de Revitalização  AR/GSA/UAR',
'Unidade de Gestão de Recursos Hídricos  AR/GSA/URH' => 'Unidade de Gestão de Recursos Hídricos  AR/GSA/URH',
'Gerência de Desenvolvimento Territorial  AR/GDT' => 'Gerência de Desenvolvimento Territorial  AR/GDT',
'Unidade de Recursos Pesqueiros e Aquicultura  AR/GDT/UPA' => 'Unidade de Recursos Pesqueiros e Aquicultura  AR/GDT/UPA',
'Unidade de Arranjos Produtivos  AR/GDT/UAP' => 'Unidade de Arranjos Produtivos  AR/GDT/UAP',
'ÁREA DE GESTÃO DOS EMPREENDIMENTOS DE IRRIGAÇÃO  AI' => 'ÁREA DE GESTÃO DOS EMPREENDIMENTOS DE IRRIGAÇÃO  AI',
'Secretaria Executiva  AI/SE' => 'Secretaria Executiva  AI/SE',
'Gerência de Gestão dos Empreendimentos de Irrigação  AI/GEI' => 'Gerência de Gestão dos Empreendimentos de Irrigação  AI/GEI',
'Gerência de Apoio à Produção  AI/GAP' => 'Gerência de Apoio à Produção  AI/GAP',
'Gerência de Administração Fundiária  AI/GAF' => 'Gerência de Administração Fundiária  AI/GAF',
'ÁREA DE DESENVOLVIMENTO INTEGRADO E INFRAESTRUTURA  AD' => 'ÁREA DE DESENVOLVIMENTO INTEGRADO E INFRAESTRUTURA  AD',
'Secretaria Executiva  AD/SE' => 'Secretaria Executiva  AD/SE',
'Gerência de Estudos e Projetos  AD/GEP' => 'Gerência de Estudos e Projetos  AD/GEP',
'Unidade de Estudos Básicos  AD/GEP/UEB' => 'Unidade de Estudos Básicos  AD/GEP/UEB',
'Unidade de Projetos  AD/GEP/UPR' => 'Unidade de Projetos  AD/GEP/UPR',
'Gerência de Implantação de Obras  AD/GIM' => 'Gerência de Implantação de Obras  AD/GIM',
'Unidade Técnica Hidroeletromecânica  AD/GIM/UTH' => 'Unidade Técnica Hidroeletromecânica  AD/GIM/UTH',
'Unidade de Obra Civil  AD/GIM/UAC' => 'Unidade de Obra Civil  AD/GIM/UAC',
'Gerência de Concessões  AD/GCO' => 'Gerência de Concessões  AD/GCO',
'Gerência de Custos  AD/GCT' => 'Gerência de Custos  AD/GCT',
'ÁREA DE GESTÃO ESTRATÉGICA  AE' => 'ÁREA DE GESTÃO ESTRATÉGICA  AE',
'Secretaria Executiva  AE/SE' => 'Secretaria Executiva  AE/SE',
'Gerência de Planejamento e Estudos Estratégicos  AE/GPE' => 'Gerência de Planejamento e Estudos Estratégicos  AE/GPE',
'Unidade de Apoio ao Planejamento Regional  AE/GPE/UPP' => 'Unidade de Apoio ao Planejamento Regional  AE/GPE/UPP',
'Unidade de Monitoramento e Avaliação  AE/GPE/UAV' => 'Unidade de Monitoramento e Avaliação  AE/GPE/UAV',
'Unidade de Controle de Contratos e Convênios  AE/GPE/UCC' => 'Unidade de Controle de Contratos e Convênios  AE/GPE/UCC',
'Unidade de Gestão de Processos  AE/GPE/UGP' => 'Unidade de Gestão de Processos  AE/GPE/UGP',
'Unidade de Suporte Geotecnológico  AE/GPE/USG' => 'Unidade de Suporte Geotecnológico  AE/GPE/USG',
'Gerência de Gestão Orçamentária  AE/GGO' => 'Gerência de Gestão Orçamentária  AE/GGO',
'Unidade de Programação Orçamentária  AE/GGO/UPO' => 'Unidade de Programação Orçamentária  AE/GGO/UPO',
'Unidade de Execução Orçamentária  AE/GGO/UEO' => 'Unidade de Execução Orçamentária  AE/GGO/UEO',
'Gerência de Tecnologia da Informação  AE/GTI' => 'Gerência de Tecnologia da Informação  AE/GTI',
'Unidade de Sistemas de Informações  AE/GTI/USI' => 'Unidade de Sistemas de Informações  AE/GTI/USI',
'Unidade de Infraestrutura e Tecnologia  AE/GTI/UIT' => 'Unidade de Infraestrutura e Tecnologia  AE/GTI/UIT',
'Unidade de Documentação e Informação  AE/GTI/UDI' => 'Unidade de Documentação e Informação  AE/GTI/UDI',
'Unidade de Governança de Tecnologia da Informação  AE/GTI/UGT' => 'Unidade de Governança de Tecnologia da Informação  AE/GTI/UGT',
'ÁREA DE GESTÃO ADMINISTRATIVA E SUPORTE LOGÍSTICO  AA' => 'ÁREA DE GESTÃO ADMINISTRATIVA E SUPORTE LOGÍSTICO  AA',
'Secretaria Executiva  AA/SE' => 'Secretaria Executiva  AA/SE',
'Gerência de Patrimônio, Material e Serviços Auxiliares  AA/GSA' => 'Gerência de Patrimônio, Material e Serviços Auxiliares  AA/GSA',
'Unidade de Serviços Auxiliares  AA/GSA/USA' => 'Unidade de Serviços Auxiliares  AA/GSA/USA',
'Unidade de Patrimônio e Material  AA/GSA/UPM' => 'Unidade de Patrimônio e Material  AA/GSA/UPM',
'Unidade de Acervos Documentais  AA/GSA/UAD' => 'Unidade de Acervos Documentais  AA/GSA/UAD',
'Gerência de Finanças  AA/GFN' => 'Gerência de Finanças  AA/GFN',
'Unidade de Programação e Execução Financeira  AA/GFN/UEF' => 'Unidade de Programação e Execução Financeira  AA/GFN/UEF',
'Unidade de Gestão da Cobrança  AA/GFN/UCB' => 'Unidade de Gestão da Cobrança  AA/GFN/UCB',
'Gerência de Contabilidade  AA/GCB' => 'Gerência de Contabilidade  AA/GCB',
'Unidade de Execução Contábil  AA/GCB/UEC' => 'Unidade de Execução Contábil  AA/GCB/UEC',
'Unidade de Escrituração e Revisão Contábil  AA/GCB/UER' => 'Unidade de Escrituração e Revisão Contábil  AA/GCB/UER',
'Gerência de Gestão de Pessoas  AA/GGP' => 'Gerência de Gestão de Pessoas  AA/GGP',
'Unidade de Desenvolvimento de Pessoas  AA/GGP/UDP' => 'Unidade de Desenvolvimento de Pessoas  AA/GGP/UDP',
'Unidade de Relações de Trabalho  AA/GGP/URT' => 'Unidade de Relações de Trabalho  AA/GGP/URT',
'Unidade de Cadastro e Pagamento  AA/GGP/UCP' => 'Unidade de Cadastro e Pagamento  AA/GGP/UCP',
'Unidade de Benefícios e Saúde Ocupacional  AA/GGP/UBS' => 'Unidade de Benefícios e Saúde Ocupacional  AA/GGP/UBS'

);

$paramsDatas = array(
				    //    'label' => 'Data de Entrada',
				        'dateFormat' => 'DMY',
				        'timeFormat' => '24',
				        'minYear' => date('Y') - 2,
				        'maxYear' => date('Y') + 5,
				        'monthNames' => array(
				                1 => "Janeiro", 2 => "Fevereiro", 3 => "Março",
				                4 => "Abril", 5 => "Maio", 6 => "Junho",
				                7 => "Julho", 8 => "Agosto", 9 => "Setembro",
				                10 => "Outubro", 11 => "Novembro", 12 => "Dezembro"
				        )
		);
